# Generated by Django 5.1.2 on 2024-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasword', models.CharField(max_length=30)),
                ('nombreUser', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
