# Generated by Django 5.1.1 on 2024-10-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreUser',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
