# Generated by Django 5.1.1 on 2024-10-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_nombreuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombreUser',
            field=models.CharField(max_length=30),
        ),
    ]
